# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='sender',
            field=models.CharField(choices=[('you', 'You'), ('them', 'Them')], max_length=12),
        ),
    ]
