# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='contacts.Contact'),
        ),
    ]
