language: python
python:
  - "2.7"
  - "3.5"

services:
  - postgresql

before_script:
  - psql -c "create database pyphon_db;" -U postgres

# command to install dependencies
install:
  - pip install --upgrade pip setuptools
  - pip install six==1.10.0
  - pip install -r requirements.pip
  - pip install coveralls

# command to run tests
script: 
  - python pyphon/manage.py migrate
  - cd pyphon
  - coverage run ./manage.py test

after_success:
  - coveralls

notifications:
  email: false