# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
    ]
