# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_auto_20170213_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('incoming', 'incoming'), ('outgoing', 'outgoing')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('no-answer', 'no-answer'), ('completed', 'completed'), ('canceled', 'canceled'), ('busy', 'busy'), ('failed', 'failed'), ('other', 'other')], max_length=10, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='contacts.Contact')),
            ],
        ),
    ]
